channels:
- conda-forge
dependencies:
- python=3.11.4
- pip<=25.3
- pip:
  - mlflow==3.8.1
  - cloudpickle==3.1.2
  - feature-engine==1.9.3
  - numpy==1.25.0
  - pandas==2.3.3
  - psutil==5.9.5
  - scikit-learn==1.5.1
  - scipy==1.14.0
name: mlflow-env
